#!/usr/bin/env bash

# Don't forget to CHMOD all hooks with permission rwxr-x--- (0750)
# $ chmod 0750 post-receive* 

while read oldrev newrev refname; do
   /var/lib/gitolite/.gitolite/hooks/common/post-receive.gitlab
   /var/lib/gitolite/.gitolite/hooks/common/post-receive.redmine
   # Other post-receive hooks
   # Please consider to comment the while loop in the hook scripts
   # /var/lib/gitolite/.gitolite/hooks/common/post-receive.email
   # ...
done

